name: fintrack_expense_tracker
description: "Smart Expense & Budget Tracker App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2   # Web-compatible key-value storage
  intl: ^0.19.0                # Date formatting
  fl_chart: ^0.68.0            # Charts for analytics
  firebase_core: ^3.9.0        # Firebase core
  firebase_auth: ^5.3.4        # Firebase authentication

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
